# This theme is based on https://github.com/jekyll/minima
# Please refer above link to know the available configurations

title: "Denture Design Studion"
remote_theme: cepdnaclk/e20-co227-Denture-Design-Studio
description: "A graphical platform that enables denture design practice"
markdown: kramdown

kramdown:
  parse_block_html: true
  syntax_highlighter_opts:
    block:
      line_numbers: false
